name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential nasm xorriso grub2-common grub-common mtools

      - name: Build project
        run: make

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: main.iso
          path: main.iso # specify the path to the artifact

      - name: Clean up build artifacts
        run: make clean
